apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-role-binding
  namespace: argo
subjects:
- kind: ServiceAccount
  name: argo-service-account
  namespace: argo
roleRef:
  kind: Role
  name: argo-service-account
  apiGroup: rbac.authorization.k8s.io
